default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  reconnect: false

development:
  <<: *default
  database: ecapp
  username: ecapp
  password: password
  host: 127.0.0.1

production:
  <<: *default
  database: ecapp
  username: ecapp
  password: password
  host: 127.0.0.1


